Split Orb
PicturePipe/sentry-cli-orb pull request #8
Opened 2019-03-05 11:24 UTC by keimlink

Split orb into several files to improve readability.

Depends on #7.

2019-03-05 17:05 UTC, cfra requested changes
I think this is a useful change, given the orb size. :+1: 

There are two minor concerns I spotted during review.

2019-03-05 17:05 UTC, cfra commented on src/examples/testing-staging-production-pipeline.yml
> +        - sentry-cli/create-deployment:
I think having a name for this instance of the job would be useful, so that it becomes obvious that this also relates only to staging. Also, this will give the job a nicer name in CircleCI's UI, otherwise the jobs will be called `sentry-cli/create-deployment#1`, `sentry-cli/create-deployment#2` and `sentry-cli/create-deployment#3`.

2019-03-05 17:05 UTC, cfra commented on src/commands/@commands.yml
> +          if [ "$(git describe --tags 2>/dev/null)" ]; then
What is this check supposed to do?
```suggestion
          if [ -n "$(git describe --tags 2>/dev/null)" ]; then
```
Maybe also even simpler:
```suggestion
          if git describe --tags > /dev/null 2>&1; then
```

2019-03-15 13:42 UTC, keimlink commented on src/examples/testing-staging-production-pipeline.yml
> +        - sentry-cli/create-deployment:
Good idea! Added the names.

2019-03-15 13:43 UTC, keimlink commented
@cfra Pull request is now ready for review. Please review again. 🙏

2019-03-15 14:06 UTC, cfra commented
I don't have `99beb9b` available locally and github won't let me download it. So I cannot really tell what changed since my review.

2019-03-15 14:15 UTC, cfra approved these changes
My previous comments have been addressed, however I cannot tell if anything else has changed without going through the whole diff again, so I will leave the merge up to you.

2019-03-15 21:54 UTC, keimlink commented
@cfra Sorry! I thought force-pushing would not completely erase the review. 😬

2019-03-15 21:54 UTC, merged